services:
  echo:
    baseUrl: http://${SPINNAKER_ECHO_HOST}:8089

jenkins:
  enabled: true
  masters:
    -
      name: aig-jenkins # The display name for this server
      address: https://jenkins.aig.com/
      username: aaa
      password: bbb


spinnaker:
  build:
    pollInterval: 15

server:
  port: 8088

redis:
  connection: redis://${SPINNAKER_REDIS_HOST}:6379

endpoints.health.sensitive: false

